### ISSUE TITLE
reduce task "Cannot read property 'requirements' of undefined"

### ISSUE THREAD

**Issue by monte-hayward** [Munter/generator-greenfield#2]
Running with dev/livestyle is seamless, thanks!

Am I missing a version or dependency for the build task?

I get the error at bottom upon `grunt -dv build --force`. The reduce task goes to 97%.
A grep of the project shows '.requirements' in two files:
   autoprefixer-core/lib/browsers.js
   asset-graphbuilder/lib/transforms/buildProduction.js

Before reaching the error at bottom, I resolved a number of unmet dependencies. using `npm install *`:
Warning: Cannot find module 'assetgraph' Use --force to continue.
Warning: Cannot find module 'lodash' Use --force to continue.
Warning: Cannot find module 'lodash' Use --force to continue.
Warning: The 'browsers' option requires the autoprefixer module to be available. Please install it in the containing project.
Cannot find module 'caniuse-db/features-json/transforms2d' Use --force to continue.

Error message
-------------------
Running "reduce" task
Task source: /path/toproject/node_modules/grunt-reduce/tasks/grunt-reduce.js
Warning: Cannot read property 'requirements' of undefined Used --force, continuing.

Done, but with warnings.

**Comment by Munter** [comment]
Sounds related to this bug, caused by an API change in Autoprefixer in v5.x that we haven't merged in compatibility for yet: https://github.com/assetgraph/assetgraph-builder/issues/168

Are you by any chance running Autoprefixer >5.x ?

**Comment by Munter** [comment]
Just merged that PR in and released assetgraph-builder v3.3.3. You should be able to get it in your project with `npm install -f grunt-reduce`.

Could you try that and see if it solves your problem?

**Comment by monte-hayward** [comment]
Thanks, @Munter! 
grunt-reduce is running now. 
...
 ✔ 0.000 secs: compileLessToCss
 ✔ 0.000 secs: removeRelations

re: autoprefixer, it appears that grunt-livestyle is running "version": "3.0.1",
and the topmost autoprefixer is   "version": "5.1.1",

**Comment by monte-hayward** [comment]
the reduce task gets to this output in seconds, then uses little cpu and makes no output for >10 minutes.
 ✔ 0.000 secs: compileLessToCss
 ✔ 0.000 secs: removeRelations

**Comment by monte-hayward** [comment]
my last comment appears unrelated to this issue.

See https://github.com/assetgraph/assetgraph-builder/issues/162
